from typing import Optional
import numpy as np
import numpy.typing as npt

class CartPole:
    def __init__(self, seed: Optional[int] = None) -> None: ...
    def step(self, action: int) -> dict[str, object]:
        """Returns {"obs": np.ndarray, "reward": float, "terminated": bool, "truncated": bool}"""
        ...
    def reset(self, seed: Optional[int] = None) -> npt.NDArray[np.float32]: ...
    def render(self) -> Optional[str]: ...

class VecEnv:
    def __init__(self, n: int, seed: Optional[int] = None) -> None: ...
    def num_envs(self) -> int: ...
    def step_all(self, actions: list[int]) -> dict[str, object]:
        """Returns {"obs": np.ndarray, "rewards": np.ndarray, "terminated": np.ndarray, "truncated": np.ndarray}"""
        ...
    def reset_all(self, seed: Optional[int] = None) -> npt.NDArray[np.float32]: ...

class GymEnv:
    def __init__(self, env: object) -> None: ...
    def step(self, action: object) -> dict[str, object]: ...
    def reset(self, seed: Optional[int] = None) -> object: ...
